#%RAML 1.0 Library
usage: library datatypes for both process and system api

types:

  fetch-single-library-response-system : !include exchange_modules/d2b7b596-411c-4921-ab42-736e52d9dab1/fetch-single-library-response-system-datatype/1.0.0/fetch-single-library-response-system-datatype.raml

  fetch-single-library-response-process : !include exchange_modules/d2b7b596-411c-4921-ab42-736e52d9dab1/fetch-single-library-response-process-datatype/1.0.0/fetch-single-library-response-process-datatype.raml

  fetch-all-library-response-system : !include exchange_modules/d2b7b596-411c-4921-ab42-736e52d9dab1/fetch-all-library-response-system-datatype/1.0.0/fetch-all-library-response-system-datatype.raml

  fetch-all-library-response-process : !include exchange_modules/d2b7b596-411c-4921-ab42-736e52d9dab1/fetch-all-library-response-process-datatype/1.0.0/fetch-all-library-response-process-datatype.raml

  add-update-request-system : !include exchange_modules/d2b7b596-411c-4921-ab42-736e52d9dab1/add-update-library-request-system/1.0.0/add-update-library-request-system.raml

  add-update-delete-200-response-system  : !include exchange_modules/d2b7b596-411c-4921-ab42-736e52d9dab1/add-update-delete-library-200-response-system-datatype/1.0.0/add-update-delete-library-200-response-system-datatype.raml