#%RAML 1.0 Library
usage: library datatypes for both process and system api

types:
  fetch-single-system: !include exchange_modules/67aaa93a-e299-44df-845d-3cdc46a34dcc/library-response-fetch-single-datatype-system/1.0.0/library-response-fetch-single-datatype-system.raml

  fetch-single-process: !include exchange_modules/67aaa93a-e299-44df-845d-3cdc46a34dcc/fetch-library-single-response-process-datatype/1.0.0/fetch-library-single-response-process-datatype.raml

  fetch-all-system: !include exchange_modules/67aaa93a-e299-44df-845d-3cdc46a34dcc/library-response-fetch-all-datatype/1.0.0/library-response-fetch-all-datatype.raml

  fetch-all-process: !include exchange_modules/67aaa93a-e299-44df-845d-3cdc46a34dcc/fetch-libraies-all-response-process-datatype/1.0.0/fetch-libraies-all-response-process-datatype.raml

  add-update-delete-response: !include exchange_modules/67aaa93a-e299-44df-845d-3cdc46a34dcc/library-200-response-add-update-delete-datatype/1.0.0/library-200-response-add-update-delete-datatype.raml

  add-update-request: !include exchange_modules/67aaa93a-e299-44df-845d-3cdc46a34dcc/library-request-add-update-datatype/1.0.0/library-request-add-update-datatype.raml